version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
     restart: always
     ports:
                - "3306:3306" 
     environment:
       MYSQL_ROOT_PASSWORD: someword
   
volumes:
    db_data:
